# Generated by Django 3.2.7 on 2021-10-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('brand', models.CharField(max_length=255)),
                ('ram_type', models.CharField(max_length=10)),
                ('ram_capacity', models.IntegerField(default=0)),
                ('ssd_present', models.BooleanField(default=False)),
                ('ssd_capacity', models.IntegerField(default=0)),
                ('hdd_present', models.BooleanField(default=False)),
                ('hdd_capacity', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('laptop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laptopapp.laptopmodel')),
            ],
        ),
    ]
