# Generated by Django 3.2.7 on 2021-10-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopmodel',
            name='hdd_capacity',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='laptopmodel',
            name='ssd_capacity',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
