# Generated by Django 3.2.7 on 2021-10-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapp', '0004_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='end_data',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='start_data',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_price',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
