# Generated by Django 3.2.7 on 2021-10-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapp', '0007_auto_20211004_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('IP', 'In Process'), ('OW', 'On the Way'), ('WC', 'With Customer'), ('C', 'Completed'), ('R', 'Rejected')], default='IP', max_length=2),
        ),
    ]
